### ISSUE TITLE
Bundling failed on RN 0.57.4

### ISSUE THREAD

**Issue by MaciekLeks** [ptomasroos/react-native-multi-slider#96]
Does `ptomasroos/react-native-multi-slider` work with RN 0.57.4? 
I get the following error with the bundler: <pre>Error: Unable to resolve module `react-native-multi-slider` from `/home/user/... : Module `react-native-multi-slider` does not exist in the Haste module map 

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/home/user/react-native/.../node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at ResolutionRequest.resolveDependency (/home/user/react-native/.../node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (/home/user/react-native/.../node_modules/metro/src/node-haste/DependencyGraph.js:219:16)
    at Object.resolve (/home/user/react-native/.../node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/home/user/react-native/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/user/react-native/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /home/user/react-native/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/home/user/react-native/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
 DELTA  [android, dev] ./index.js ▓▓▓▓▓▓▓▓░░░░░░░░ 53.2% (679/931), failed.

::ffff:127.0.0.1 - - [12/Nov/2018:18:51:33 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.11.0"

</pre>

Related issue in the error suggested that there is such an issue, but following the link shows the issue should be resolved with RN 0.57.

P.S. Unfortunately I hadn't check if it worked with RN 0.56, before I upgraded to RN 057.4.

**Comment by ptomasroos** [comment]
We're using it with 0.57.4 in production already.
You need to show me some code if I should be able to help out sadly.

But i'm pretty sure you importing the wrong package.

from '@ptomasroos/react-native-multi-slider'; is the correct one

**Comment by ptomasroos** [comment]
Yes that’s my bad as I’m on my way to change the package name but haven’t completed it. Sorry!

**Comment by asjustis** [comment]
I know I'm posting this to a closed issue, but getting the same story with RN 0.55.4 -> @ptomasroos any clue if this could work without an update?

**Comment by ptomasroos** [comment]
Import from '@ptomasroos/react-native-multi-slider';

**Comment by ptomasroos** [comment]
Will work fine

**Comment by asjustis** [comment]
Ooooh you meant `import`, not the `npm install`... 🤦‍♂️  It works indeed, thanks for the support!

**Comment by Dror-Bar** [comment]
Might want to add this line to "Usage" in the readme:
`Import from '@ptomasroos/react-native-multi-slider';`
